import Foundation

/// Synthesizes a documented default `athena.toml` when `athena install`
/// is run without a config to point at. Pure (no filesystem, no env):
/// every knob is a parameter defaulted to the built-in default, so the
/// SAME values flow into both the written file and the parsed
/// `AthenaConfig` (parse the output to obtain the config — they cannot
/// drift). Optional keys are emitted commented so the daemon's built-in
/// defaults apply until the operator edits them.
public enum DefaultConfig {
    /// `listenPort` and `logDir` have no universal default here (the
    /// caller supplies the appliance's port — Athena's own 7447 — and a
    /// prefix-derived log dir), so they are required parameters.
    public static func toml(
        listenHost: String = "127.0.0.1",
        listenPort: Int,
        engine: String = "mlx",
        logDir: String
    ) -> String {
        """
        # ─────────────────────────────────────────────────────────────
        #  Athena daemon configuration (synthesized defaults)
        # ─────────────────────────────────────────────────────────────
        #  Generated by `athena install` because no config was supplied.
        #  Edit freely, then `athena config set <key> <value>` or
        #  reinstall. Schema: flat `key = value` scalars only — no
        #  tables/arrays. `#` starts a comment; a commented key falls
        #  back to the daemon's built-in default. Strings are quoted;
        #  ints/bools/floats are bare.
        # ─────────────────────────────────────────────────────────────


        # ── Network ──────────────────────────────────────────────────
        listen_host = "\(listenHost)"
        listen_port = \(listenPort)


        # ── Model ────────────────────────────────────────────────────
        # LLM engine: "mlx" (real Qwen3.5 from the store) or "stub".
        engine = "\(engine)"
        # LLM dir path or a name under the model store. No hard default —
        # pull one (`athena pull`) and select it (`athena default`).
        # model = "Qwen3.5-27B-4bit-mtp"
        # Model-store ROOT. Commented ⇒ "~/.athena/models" of the
        # daemon's user. Set to relocate the store (e.g. an external SSD).
        # model_store = "/Volumes/<your-disk>/mlx-models"


        # ── Inference tuning (commented ⇒ built-in default) ───────────
        # max_tokens = 1024
        # temperature = 0.7
        # speculative = false
        # KV-cache compression: "none" | "turboquant" | "triattention".
        # kv_compression = "none"

        # ── [prompt_cache] cross-request prompt-prefix KV reuse (M59) ──
        # Transparent reuse of a previously-computed KV prefix across chat
        # completions that share a leading token run (e.g. a static system
        # prompt + verbatim document, varying only in the trailing
        # instruction). MTP/speculative path only; bit-identical to a cold
        # prefill. Default OFF. The ATHENA_PROMPT_CACHE env var
        # (1/true/0/false) overrides prompt_cache_enabled at startup.
        # The pool is governed: bounded by entry count, a byte cap
        # (default = the governor prompt-cache cap), and an idle-TTL, and
        # is shed under memory pressure before any module is evicted.
        # prompt_cache_enabled = false
        # prompt_cache_max_entries = 4
        # prompt_cache_max_bytes = 0          # 0 ⇒ governor-derived
        # prompt_cache_idle_ttl_secs = 600
        # Scope: "principal" (never reuse across callers — the secure
        # default), "cache_key" (key by the OpenAI prompt_cache_key hint),
        # or "both". The resident model id is always part of the key.
        # prompt_cache_scope = "principal"


        # ── Storage ──────────────────────────────────────────────────
        # Embedded SQLite store (auth/audit/usage + queue). Commented ⇒
        # "~/.athena" of the daemon's user.
        # data_dir = "/usr/local/var/athena/data"


        # ── Memory governor ──────────────────────────────────────────
        # Global Metal/MLX budget in bytes. Commented ⇒ 75% of RAM.
        # budget_bytes = 36000000000


        # ── Security ─────────────────────────────────────────────────
        # Bearer-token keys file. Commented + loopback ⇒ auth OFF (dev);
        # commented + non-loopback ⇒ the daemon REFUSES to start.
        # auth_keys_file = "/usr/local/etc/athena/auth.keys"
        # In-daemon TLS (HTTPS). Set BOTH (cert chain + private key, PEM);
        # only one ⇒ a hard startup error. Commented ⇒ plaintext HTTP
        # (loopback or a TLS reverse proxy only — see docs/reverse-proxy.md).
        # tls_cert = "/usr/local/etc/athena/tls/fullchain.pem"
        # tls_key  = "/usr/local/etc/athena/tls/privkey.pem"


        # ── Network (egress proxy) ───────────────────────────────────
        # Route the model-weight fetch (the only outbound) through a
        # proxy. The *_PROXY env vars always win; these only fill gaps.
        # https_proxy = "http://proxy.corp.example:3128"
        # http_proxy  = "http://proxy.corp.example:3128"
        # all_proxy   = "socks5://proxy.corp.example:1080"
        # no_proxy    = "127.0.0.1,localhost,.internal.example"


        # ── Logging ──────────────────────────────────────────────────
        # Crash-dump capture file under launchd (StandardErrorPath).
        # The diagnostic surface is the macOS unified log — query via
        # `log show --predicate 'subsystem == "athena"'`. M45.1
        # dropped per-sink stdout/file/UDP shippers; off-box shipping
        # is now an operator concern (FluentBit / vector.dev against
        # subsystem "athena").
        log_dir = "\(logDir)"
        # Foreground terminal verbosity (no effect under launchd; the
        # unified log captures everything regardless). Use
        # `sudo log config --mode "level:debug" --subsystem athena`
        # to tune the unified-log gate at runtime without a restart.
        # log_level = "info"
        """
    }
}
